name: client
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies: 
  crypto: ^3.0.1
  dio: ^4.0.4
  equatable: ^2.0.3
  json_annotation: ^4.4.0
  
dev_dependencies:
  test: ^1.19.2
  very_good_analysis: ^2.4.0
  build_runner: ^2.1.5
  json_serializable: ^6.1.1
  